import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import Fastify from "fastify";
import { describe, expect, it } from "vitest";
import { createSessionToken } from "./local-auth.js";
import { registerPackageSyncRoute } from "./package-sync-route.js";
const approvedPackage = { formatVersion: 1, day: { date: "2026-08-30", timezone: "America/Sao_Paulo" }, status: "APPROVED", packageVersion: "1", generatedAt: "2026-08-30T12:00:00-03:00", checksum: "sha256:example", sourceEvidence: [{ sourceId: "fixture", contentHash: "hash", collectedAt: "2026-08-30T12:00:00-03:00", parserVersion: "1", decisionRule: "fixture" }], celebration: { title: "Teste", season: "Tempo Comum", color: "Verde", cycleYear: "B", celebrationRank: "Domingo", readings: [{ type: "GOSPEL", citation: "Referencia" }], massFlow: [{ section: "introductory-rites", note: "Nota" }], selectedSongs: [], sourceReference: { booklet: "Livreto" } } };
describe("package sync route", () => { it("requires a session and serves only an approved matching package", async () => { const directory = await mkdtemp(join(tmpdir(), "missa-sync-sync-")); const app = Fastify(); registerPackageSyncRoute(app, "secret", directory, "development-token"); try { await writeFile(join(directory, "2026-08-30__America_Sao_Paulo.json"), JSON.stringify(approvedPackage)); expect((await app.inject({ method: "GET", url: "/v1/packages/2026-08-30?timezone=America/Sao_Paulo" })).statusCode).toBe(401); const cookie = `missa_sync_session=${createSessionToken("secret")}`; expect((await app.inject({ method: "GET", url: "/v1/packages/2026-08-30?timezone=America/Sao_Paulo", headers: { cookie } })).statusCode).toBe(200); expect((await app.inject({ method: "GET", url: "/v1/packages/daily/2026-08-30?timezone=America/Sao_Paulo", headers: { authorization: "Bearer development-token" } })).statusCode).toBe(200); } finally { await app.close(); await rm(directory, { recursive: true, force: true }); } }); });
